### ISSUE TITLE
Poprawa instrukcji warunkowych

### ISSUE THREAD

**Issue by EmOlsz** [orzel095/oddaj_rzeczy#3]
https://github.com/orzel095/oddaj_rzeczy/blob/c7ff2fb13434f0bcde6482102c6cbef48603ec53/src/components/sign/Sign-in.js#L83

Nie uważasz, że mamy możliwość ładniejszego zapisu? Zaproponowałbym : 
{errors.email && touched.email && <div className="form-alert">{errors.email}</div>}
Zauważ, że w takim wypadku renderujemy element div tylko wtedy, gdy wcześniejszcze warunki zostały spełnione, w przeciwnym wypadku pomijamy kod. Mała zmiana, ale nie zwracamy nadmiarowego nulla :)
Do poprawy analogiczne zapisy w pliku Sign-up.js

**Comment by orzel095** [comment]
Masz racje, zaproponowany zapis jest bardziej elegancki :)
